version: '3.7'
services:
  fastapi-scheduler:
    image: scheduler-fastapi:latest
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:password@localhost/postgres
    network_mode: "host"  
  postgres:
    image: postgres:12.4
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    